# -*- coding: utf-8 -*-
# Generated by Django 1.11.15.dev20190208030303 on 2019-02-12 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreference',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='marketingpreference',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marketingpreference',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
